#+TITLE: Ralphie

A set of tools for cli and keybindings, written in
Clojure/[[https://github.com/borkdude/babashka/][Babashka]].

* Ralphie

#+BEGIN_SRC A Christmas Story
    Ralphie as Adult: [narrating] Meanwhile, I struggled for exactly the right
    BB gun hint. It had to be firm, but subtle.

    Ralphie: Flick says he saw some grizzly bears near Pulaski's candy store!

    [Everyone stares at Ralphie]

    Ralphie as Adult: [narrating] They looked at me as if I had lobsters
    crawling out of my ears.
#+END_SRC

Maybe the bears are real, maybe not. Either way, Ralphie knew he wanted to shoot
a BB gun, same as I knew I wanted to write a tool in Babashka.

* Features
** ~run-command~
Opens rofi with all available commands. Runs the selected one.
#+BEGIN_SRC sh
ralphie rofi
#+END_SRC

#+BEGIN_SRC i3
bindsym $mod+r exec --no-startup-id ralphie rofi
#+END_SRC
** ~open-term~: open tmux for current workspace
Opens alacritty+tmux in the current workspace,
using the workspace name as the tmux session name.
#+BEGIN_SRC sh
ralphie open-term
#+END_SRC

#+BEGIN_SRC i3
bindsym $mod+Return exec --no-startup-id ralphie open-term
#+END_SRC
** ~install~
Installs ~ralphie~ by symlinking ~src/ralphie/core.clj~ to
~~/.local/bin/ralphie~
TODO expand to write bindings to i3/config.ralphie
** TODO
*** Build docs
Rebuilds this readme based on the ralphie config,
which is a compilation of every command.
*** Resize monitor resolution
*** Restart i3
*** Git Clone
*** Doctor scripts
*** Take Screenshot with metadata
*** Universal Focus Movement
*** Open Emacs for current workspace
*** Toggle scratchpad for current workspace
*** Toggle global scratchpad
* Development
run it

#+BEGIN_SRC zsh
bb --classpath src --main ralphie.core -- -h
#+END_SRC

run an nrepl server to connect to.

#+BEGIN_SRC zsh
rlwrap bb -cp src --nrepl-server 1667
#+END_SRC
