name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@e73bf2b6435244b2c9c5c226ae5022d91d0ce702
        with:
          tools-deps: latest
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-clj
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Run Tests
        run: clj -M:test

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2020.04.05'

    - uses: actions/checkout@v2

    - name: Lint
      run: clj-kondo --lint src:test --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
